# Travis-CI config
language: cpp

compiler:
- gcc
- clang

script: make -C sm-zip

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y gcc-multilib g++-multilib libc6-dev-i386 lib32stdc++6 lib32z1-dev

branches:
only:
- master

notifications:
email: false
