# Travis-CI config
language: cpp
compiler:
  - gcc
  - clang

script: make CXX=clang -C sm-zip

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-multilib g++-multilib

# Use IRC notifications instead of email
notifications:
  email: false
