# Travis-CI config
language: cpp

compiler:
- gcc
- clang

-before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq gcc-multilib g++-multilib libc6-dev-i386 lib32stdc++6 lib32z1-dev

script:
- cd sm-zip
- make

branches:
only:
- master

notifications:
email: false
