# Travis-CI config for GoonPUG

language: cpp
compiler:
  - gcc
  - clang

script: "cd sm-zip && make"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-multilib g++-multilib

branches:
  only:
    - master

# Use IRC notifications instead of email
notifications:
  email: false
  irc:
    channels:
      - "irc.synirc.net#goonpug"
    on_success: always
    on_failure: always
