# Travis-CI config
language: cpp
compiler:
  - gcc
  - clang

script: make -C sm-zip

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-multilib g++-multilib llvm-3.4 llvm-3.4-dev clang

# Use IRC notifications instead of email
notifications:
  email: false
